// CONTRACT.md for a design scratch dir: the blueprint and checker sections of docs/CONTRACT.md
// ("Library on disk", "Building types", "Checker profiles", the kit part of "Kit CLI"). The sidecar
// ships without docs/, so the text is kept here; keep it in step with docs/CONTRACT.md.

const LINES = [
  '# Architect blueprint contract (excerpt for the design agent)',
  '',
  'This is the part of the Architect contract a design has to meet. BRIEF.md has the request.',
  '',
  '## Library on disk',
  '',
  'A finished design is installed by the sidecar as `<library>/<id>/`, where `<id>` matches `[a-z0-9_]+`:',
  '',
  '| file | what |',
  '|---|---|',
  '| `<id>.nbt` | vanilla structure template |',
  '| `<id>.blueprint.json` | sidecar (below) |',
  '| `<id>.mjs` | the design\'s parametric source (kept for variants and remix) |',
  '| `<id>.preview-iso.png`, `-top.png`, `-front.png` | previews (optional) |',
  '',
  'You only write `kit/designs/<id>.mjs`; `node kit/build.mjs <id>` writes the `.nbt` and the sidecar, and',
  'the sidecar adds `source`, `createdAt` and `request` when it installs the design.',
  '',
  '### Sidecar `<id>.blueprint.json`',
  '',
  '```json',
  '{',
  '  "id": "gen_lakeside_cabin",',
  '  "name": "Lakeside Cabin",',
  '  "description": "A one-room log cabin with a porch and a stone chimney.",',
  '  "type": "cabin",',
  '  "tags": ["rustic", "small"],',
  '  "size": { "x": 11, "y": 9, "z": 13 },',
  '  "groundY": 1,',
  '  "front": "south",',
  '  "materials": ["minecraft:spruce_log", "..."],',
  '  "foundationBlock": "minecraft:cobblestone",',
  '  "approach": { "length": 4, "width": 3, "block": "minecraft:dirt_path", "slab": "minecraft:cobblestone_slab" },',
  '  "interior": { "minX": 1, "minY": 1, "minZ": 1, "maxX": 9, "maxY": 6, "maxZ": 11 },',
  '  "anchors": {',
  '    "entrance": { "x": 5.5, "y": 1.0, "z": 12.5, "yaw": 0.0, "pitch": 0.0 },',
  '    "spawn":    { "x": 5.5, "y": 1.0, "z": 14.5, "yaw": 180.0, "pitch": 0.0 },',
  '    "cam_overview": { "x": -6.0, "y": 10.0, "z": 22.0, "yaw": -140.0, "pitch": 25.0 }',
  '  },',
  '  "source": "gen_lakeside_cabin.mjs",',
  '  "createdAt": 1759600000000,',
  '  "request": { "...": "the DesignRequest it was made from (absent for bundled)" }',
  '}',
  '```',
  '',
  '- `size`: the template size. `groundY`: the feet row (row groundY-1 is the floor). `front`: the side the',
  '  entrance faces. `foundationBlock`: what the mod fills below the floor down to the ground when it places',
  '  the design on uneven terrain. `approach`: the path the mod lays from the entrance outwards.',
  '- `interior` (optional): the box of the inside; the checker uses it for light, reachability and enclosure.',
  '- Coordinates are relative to the template origin (its minimum corner); +x east, +y up, +z south.',
  '- Templates contain vanilla blocks only. Required anchors: `entrance` and `spawn`. `cam_*` anchors are optional.',
  '',
  '## Building types (`type`)',
  '',
  '`house`, `cabin`, `cottage`, `tower`, `shop`, `tavern`, `barn`, `smithy`, `chapel`, `gatehouse`, `custom`.',
  'Each type has a checker profile.',
  '',
  '## Checker profiles (kit/lib/check.mjs)',
  '',
  'The checker reads `type` from the sidecar and applies the common rules plus the profile. It runs as',
  '`node kit/build.mjs <id>` (build + check, prints `check: OK` or errors); the sidecar re-runs it with',
  '`--max x,y,z` (the size limit) and `--type <t>` (the expected type).',
  '',
  'Severity: palette validity, door + buttons, light, anchor standability and size are errors. Floating',
  'blocks, reachability, enclosure, the profile geometry and interior volume are warnings for now: fix them',
  'anyway, a warning is a flaw a player will notice.',
  '',
  'Common:',
  '- vanilla `minecraft:` blocks only, all of them in `kit/lib/blocks.mjs`; every property explicit and valid',
  '- `entrance` and `spawn` anchors present, with a standable cell (solid below, 2 free cells above)',
  '- at least one outside door, closed, on the `front` face reachable from `entrance`; an iron door',
  '  needs a button on both sides, a wooden door doesn\'t',
  '- nothing floating: every non-air block is connected to the ground row through other blocks (face',
  '  adjacency; attachables count through their support)',
  '- `interior` (when present): every standable interior cell is lit by vanilla emitters (block light >= 1),',
  '  every floor level is reachable from the entrance by walking (stairs, ladders, slabs; max step 1),',
  '  and the interior is enclosed (no sky access straight down into it except declared skylights/courtyards)',
  '- size within `--max`',
  '',
  'Profiles:',
  '- `tower`: height >= 2 x the smaller footprint side; >= 3 floor levels reachable',
  '- `barn`: an entrance opening at least 3 wide and 3 tall (a door or an open arch)',
  '- `gatehouse`: a passage through the building, front to back, at least 3 wide and 3 tall',
  '- `chapel`, `tavern`, `shop`, `house`, `cottage`, `cabin`, `smithy`: the common rules plus, as a warning,',
  '  a minimum interior volume per type',
  '- `custom`: the common rules only',
  '',
  '## Kit CLI',
  '',
  'Layout: `kit/lib/` (kit.mjs, blocks.mjs, colors.mjs, check.mjs, the renderer, nbt, png), `kit/designs/<id>.mjs`',
  '(sources; `export const id`, a default export that returns the Blueprint), `kit/build.mjs`, `kit/render.mjs`.',
  '',
  '- `node kit/build.mjs <id> [--out <dir>] [--max x,y,z] [--type <t>] [--json]`: imports `kit/designs/<id>.mjs`,',
  '  writes `<out>/<id>.nbt` + `<out>/<id>.blueprint.json` (default `--out kit/out`), then checks. Prints warnings',
  '  and errors one per line and `check: OK` or `check: FAILED`; exit code 0 = OK, 1 = check failed, 2 = the',
  '  design threw / bad usage. `--json` prints one JSON line instead: `{ ok, errors[], warnings[], nbt, sidecar }`.',
  '- `node kit/render.mjs <file.nbt> --out <dir>`: writes `<id>.preview-iso.png`, `-top.png`, `-front.png`.',
  '- `kit/lib/blocks.mjs` is generated from the vanilla data: every vanilla block is usable, and it cannot be',
  '  extended here.',
  '- Kit helpers (kit/lib/kit.mjs) for general buildings: walls with openings, floors, wooden and iron doors,',
  '  gable / hip / flat roofs with overhang, stairs and ladders between floors, windows (pane rhythm), chimney,',
  '  porch, lighting helpers, `anchor()`.',
  '- Examples (hand-written, pass the checker with no warnings): `kit/designs/cabin.mjs`, `kit/designs/tower.mjs`',
  '  and any others in `kit/designs/`.',
  '',
];

export const CONTRACT_EXCERPT = LINES.join('\n');
