package dev.larattalabs.architect.design;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import net.minecraft.SharedConstants;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.server.Bootstrap;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Mirror;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.Property;
import org.junit.jupiter.api.Test;

/**
 * Slice 0b, gate item 2 ("the mirror oracle"): vanilla's {@link BlockState#mirror} for every block the kit knows (all of
 * vanilla's, kit/lib/blocks.mjs), dumped to {@code kit/test/fixtures/mirror-oracle.json}. The kit's mirror table
 * (kit/lib/mirror.mjs) is compared against it by kit/test/mirror.test.mjs.
 *
 * <p>Format: {@code classes[]} of {@code {props: [[name, [values...]]...], fb: [index...], lr: [index...], blocks: [id...]}}.
 * A state's index is mixed-radix over the props sorted by name (the last prop varies fastest), each value its position in
 * the listed values; {@code fb[i]} / {@code lr[i]} is the index of state i mirrored with FRONT_BACK (x flips) and LEFT_RIGHT
 * (z flips). Blocks whose states all mirror to themselves are listed in {@code identity}. {@code -Dmirror.write=true}
 * rewrites the fixture; otherwise the test fails when vanilla and the fixture differ.
 */
class MirrorOracleTest {
	static final Path FIXTURE = Path.of("../kit/test/fixtures/mirror-oracle.json");

	@Test
	void fixtureEqualsVanilla() throws Exception {
		SharedConstants.tryDetectVersion();
		Bootstrap.bootStrap();
		Map<String, JsonObject> classes = new LinkedHashMap<>();
		List<String> identity = new ArrayList<>();
		List<Block> blocks = new ArrayList<>();
		BuiltInRegistries.BLOCK.forEach(blocks::add);
		blocks.sort(Comparator.comparing(b -> BuiltInRegistries.BLOCK.getKey(b).toString()));
		for (Block b : blocks) {
			String id = BuiltInRegistries.BLOCK.getKey(b).toString();
			List<Property<?>> props = new ArrayList<>(b.getStateDefinition().getProperties());
			props.sort(Comparator.comparing(Property::getName));
			List<BlockState> states = b.getStateDefinition().getPossibleStates();
			int n = states.size();
			int[] fb = new int[n];
			int[] lr = new int[n];
			boolean same = true;
			BlockState[] byIndex = new BlockState[n];
			for (BlockState s : states) byIndex[index(s, props)] = s;
			for (int i = 0; i < n; i++) {
				fb[i] = index(byIndex[i].mirror(Mirror.FRONT_BACK), props);
				lr[i] = index(byIndex[i].mirror(Mirror.LEFT_RIGHT), props);
				if (fb[i] != i || lr[i] != i) same = false;
			}
			if (same) {
				identity.add(id);
				continue;
			}
			JsonArray pj = new JsonArray();
			for (Property<?> p : props) {
				JsonArray one = new JsonArray();
				one.add(p.getName());
				one.add(valueNames(p));
				pj.add(one);
			}
			JsonArray fbj = new JsonArray();
			JsonArray lrj = new JsonArray();
			for (int i = 0; i < n; i++) {
				fbj.add(fb[i]);
				lrj.add(lr[i]);
			}
			String sig = pj + "|" + fbj + "|" + lrj;
			JsonObject c = classes.get(sig);
			if (c == null) {
				c = new JsonObject();
				c.add("props", pj);
				c.add("fb", fbj);
				c.add("lr", lrj);
				c.add("blocks", new JsonArray());
				classes.put(sig, c);
			}
			c.getAsJsonArray("blocks").add(id);
		}
		JsonObject out = new JsonObject();
		out.addProperty("comment", "GENERATED by mod MirrorOracleTest (-Dmirror.write=true): vanilla BlockState.mirror for every block; do not edit");
		JsonArray cj = new JsonArray();
		classes.values().forEach(cj::add);
		out.add("classes", cj);
		JsonArray ij = new JsonArray();
		identity.forEach(ij::add);
		out.add("identity", ij);
		// compact: one class per line keeps the file small and its diffs readable
		Gson gson = new GsonBuilder().disableHtmlEscaping().create();
		StringBuilder sb = new StringBuilder("{\"comment\":").append(gson.toJson(out.get("comment"))).append(",\n\"classes\":[\n");
		for (int i = 0; i < cj.size(); i++) sb.append(gson.toJson(cj.get(i))).append(i + 1 < cj.size() ? ",\n" : "\n");
		sb.append("],\n\"identity\":").append(gson.toJson(ij)).append("}\n");
		String text = sb.toString();
		if (Boolean.getBoolean("mirror.write")) {
			Files.writeString(FIXTURE, text);
			return;
		}
		assertEquals(JsonParser.parseString(Files.readString(FIXTURE)), JsonParser.parseString(text), "kit/test/fixtures/mirror-oracle.json is stale: rerun with -Dmirror.write=true");
	}

	private static <T extends Comparable<T>> JsonArray valueNames(Property<T> p) {
		JsonArray a = new JsonArray();
		for (T v : p.getPossibleValues()) a.add(p.getName(v));
		return a;
	}

	@SuppressWarnings({"unchecked", "rawtypes"})
	private static int index(BlockState s, List<Property<?>> props) {
		int idx = 0;
		for (Property p : props) {
			List vals = p.getPossibleValues();
			idx = idx * vals.size() + vals.indexOf(s.getValue(p));
		}
		return idx;
	}
}
